locals {
  # Zero-padded IDs: ["01", "02", ..., "20"] (or whatever range is configured)
  student_ids = [
    for i in range(var.student_start_number, var.student_count + var.student_start_number) :
    format("%02d", i)
  ]
}

# ── Per-student Serverless Control Planes ────────────────────────────────────

resource "konnect_gateway_control_plane" "serverless_cp" {
  for_each = toset(local.student_ids)

  name         = "${var.student_name_prefix}${each.key}-cp"
  description  = "${var.control_plane_description} ${var.student_name_prefix}${each.key}"
  cluster_type = "CLUSTER_TYPE_SERVERLESS_V1"
  auth_type    = "pinned_client_certs"
  cloud_gateway = true
  labels       = var.control_plane_labels
}

resource "konnect_cloud_gateway_configuration" "serverless_gw" {
  for_each = toset(local.student_ids)

  control_plane_geo = var.konnect_region
  control_plane_id  = konnect_gateway_control_plane.serverless_cp[each.key].id

  dataplane_groups = [
    {
      provider = "aws"
      region   = var.konnect_region
    }
  ]

  kind = "serverless.v1"
}

# ── Config Store + Vault per student (LLM API keys) ──────────────────────────

resource "konnect_gateway_config_store" "student_config_store" {
  for_each = toset(local.student_ids)

  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
  name             = "${var.student_name_prefix}${each.key}-config-store"
}

resource "konnect_gateway_vault" "student_vault" {
  for_each = toset(local.student_ids)

  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
  name             = "konnect"
  prefix           = "ai"
  description      = "Konnect config store vault for ${var.student_name_prefix}${each.key}"
  config = jsonencode({
    config_store_id = konnect_gateway_config_store.student_config_store[each.key].id
  })
}

# ── LLM API key secrets (stored in each student's Config Store) ───────────────
# These are referenced in decK configs as {vault://ai/llm-api-key-openai} etc.
# Students never see the raw keys — Kong resolves them at request time.

resource "konnect_gateway_config_store_secret" "llm_openai" {
  for_each = toset(local.student_ids)

  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
  config_store_id  = konnect_gateway_config_store.student_config_store[each.key].id
  key              = "llm-api-key-openai"
  value            = "Bearer ${var.llm_api_key_openai}"
}

resource "konnect_gateway_config_store_secret" "llm_anthropic" {
  # Only provision if an Anthropic key has been provided (Lab 3 failover)
  # for_each = var.llm_api_key_anthropic != "" ? toset(local.student_ids) : toset([])
  for_each = toset(local.student_ids)

  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
  config_store_id  = konnect_gateway_config_store.student_config_store[each.key].id
  key              = "llm-api-key-anthropic"
  value            = "Bearer ${var.llm_api_key_anthropic}"
}

# ── expense-agent consumer + API key (pre-seeded for Lab 2+) ─────────────────

resource "konnect_gateway_consumer" "expense_agent" {
  for_each = toset(local.student_ids)

  username         = "expense-agent"
  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
}

# resource "konnect_gateway_consumer_key_auth" "expense_agent_key" {
#   for_each = toset(local.student_ids)

#   consumer_username = konnect_gateway_consumer.expense_agent[each.key].username
#   consumer_id       = konnect_gateway_consumer.expense_agent[each.key].id
#   control_plane_id  = konnect_gateway_control_plane.serverless_cp[each.key].id
#   # key is auto-generated by Konnect when omitted
# }

# ── Reference Existing Demo Control Plane for Lab 1 Agent Loop ──────────────

data "konnect_gateway_control_plane" "demo_cp" {
}

# ── Lab 1: Policy API Service ────────────────────────────────────────────────

resource "konnect_gateway_service" "policy_api_service" {
  control_plane_id = data.konnect_gateway_control_plane.demo_cp.id
  name             = "policy-api-service"
  protocol         = "http"
  host             = "mock-policy.internal"
  port             = 80
  path             = "/"
}

# Policy MCP Route with AI MCP Proxy Plugin
resource "konnect_gateway_route" "policy_mcp" {
  control_plane_id = data.konnect_gateway_control_plane.demo_cp.id
  name             = "policy-mcp"
  service = {
    id = konnect_gateway_service.policy_api_service.id
  }
  paths = ["/mcp/policy"]
}

resource "konnect_gateway_plugin_ai_mcp_proxy" "policy_mcp_ai_proxy" {
  control_plane_id = data.konnect_gateway_control_plane.demo_cp.id
  route = {
    id = konnect_gateway_route.policy_mcp.id
  }
  
  config = {
    mode = "conversion-listener"
    logging = {
      log_audits     = true
      log_payloads   = true
      log_statistics = true
    }
    max_request_body_size = 32768
    tools = [
      {
        name = "getPolicy"
        annotations = {
          title = "Get Company Policy"
        }
        description = "Returns the company-wide policy rules"
        path        = "/policy-api/policy"
        method      = "GET"
      }
    ]
  }
}

# Policy API Route with Mocking Plugin
resource "konnect_gateway_route" "policy_api_route" {
  control_plane_id = data.konnect_gateway_control_plane.demo_cp.id
  name             = "policy-api-route"
  service = {
    id = konnect_gateway_service.policy_api_service.id
  }
  paths      = ["/policy-api"]
  strip_path = true
}

resource "konnect_gateway_plugin_mocking" "policy_api_mocking" {
  control_plane_id = data.konnect_gateway_control_plane.demo_cp.id
  route = {
    id = konnect_gateway_route.policy_api_route.id
  }
  
  config = {
    include_base_path  = true
    custom_base_path   = "/policy-api"
    api_specification = <<-EOT
openapi: "3.0.3"
info:
  title: Policy Service
  description: >
    Returns company expense policy rules and evaluates whether a specific
    expense complies with them. The agent calls this service to get the
    reasoning context it needs before calling the expense service to act.
    Kong's Mocking plugin serves these example responses directly —
    no upstream service is required.
  version: "1.0.0"

paths:
  /policy:
    get:
      operationId: getPolicy
      summary: Retrieve the current expense policy
      description: >
        Returns the company-wide policy rules: approval thresholds,
        categories that require receipts, and categories that always
        require escalation regardless of amount.
      responses:
        "200":
          description: Current policy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Policy"
              example:
                autoApproveLimit: 200
                escalateThreshold: 1000
                receiptRequiredAbove: 75
                alwaysEscalateCategories:
                  - travel
                  - conference
                  - equipment
                alwaysRejectCategories:
                  - personal
                  - alcohol
                  - gambling
                version: "2025-Q2"

components:
  schemas:
    Policy:
      type: object
      properties:
        autoApproveLimit:
          type: number
          description: Expenses at or below this amount are auto-approvable (USD)
          example: 200
        escalateThreshold:
          type: number
          description: Expenses at or above this amount always require human sign-off (USD)
          example: 1000
        receiptRequiredAbove:
          type: number
          description: Receipt must be attached for expenses above this amount (USD)
          example: 75
        alwaysEscalateCategories:
          type: array
          items:
            type: string
          description: Categories that always require escalation regardless of amount
          example: [travel, conference, equipment]
        alwaysRejectCategories:
          type: array
          items:
            type: string
          description: Categories that are never reimbursable
          example: [personal, alcohol, gambling]
        version:
          type: string
          example: "2025-Q2"
EOT
  }
}

# ── Consumer groups for ACL-based tool scoping (Lab 2) ───────────────────────

resource "konnect_gateway_consumer_group" "expense_agents" {
  for_each = toset(local.student_ids)

  name             = "expense-agents"
  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
}

resource "konnect_gateway_consumer_group" "escalation_approved" {
  for_each = toset(local.student_ids)

  name             = "escalation-approved"
  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
}

resource "konnect_gateway_consumer_group_member" "agent_expense_agents" {
  for_each = toset(local.student_ids)

  consumer_id       = konnect_gateway_consumer.expense_agent[each.key].id
  consumer_group_id = konnect_gateway_consumer_group.expense_agents[each.key].id
  control_plane_id  = konnect_gateway_control_plane.serverless_cp[each.key].id
}

resource "konnect_gateway_consumer_group_member" "agent_escalation_approved" {
  for_each = toset(local.student_ids)

  consumer_id       = konnect_gateway_consumer.expense_agent[each.key].id
  consumer_group_id = konnect_gateway_consumer_group.escalation_approved[each.key].id
  control_plane_id  = konnect_gateway_control_plane.serverless_cp[each.key].id
}

# ── Global CORS plugin (one per control plane) ───────────────────────────────

resource "konnect_gateway_plugin_cors" "global_cors" {
  for_each = toset(local.student_ids)

  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
  instance_name    = "global-cors"

  config = {
    allow_origin_absent = true
    origins             = ["*"]
    methods             = ["GET", "HEAD", "PUT", "PATCH", "POST", "DELETE", "OPTIONS", "TRACE", "CONNECT"]
    credentials         = true
    max_age             = 3600
    preflight_continue  = false
  }
}

resource "konnect_gateway_plugin_cors" "demo_global_cors" {
  control_plane_id = data.konnect_gateway_control_plane.demo_cp.id
  instance_name    = "demo-global-cors"

  config = {
    allow_origin_absent = true
    origins             = ["*"]
    methods             = ["GET", "HEAD", "PUT", "PATCH", "POST", "DELETE", "OPTIONS", "TRACE", "CONNECT"]
    credentials         = true
    max_age             = 3600
    preflight_continue  = false
  }
}

# ── System account token (shared — used for decK syncs in lab instructions) ──

resource "konnect_system_account_access_token" "token" {
  account_id = var.system_account_id
  expires_at = timeadd(timestamp(), "8760h") # 1 year — refresh before next cohort
  name       = "${var.student_name_prefix}workshop-token"
}
