locals {
  # Zero-padded IDs: ["01", "02", ..., "20"] (or whatever range is configured)
  student_ids = [
    for i in range(var.student_start_number, var.student_count + var.student_start_number) :
    format("%02d", i)
  ]
}

# ── Per-student Serverless Control Planes ────────────────────────────────────

resource "konnect_gateway_control_plane" "serverless_cp" {
  for_each = toset(local.student_ids)

  name         = "${var.student_name_prefix}${each.key}-cp"
  description  = "${var.control_plane_description} ${var.student_name_prefix}${each.key}"
  cluster_type = "CLUSTER_TYPE_SERVERLESS_V1"
  auth_type    = "pinned_client_certs"
  cloud_gateway = true
  labels       = var.control_plane_labels
}

resource "konnect_cloud_gateway_configuration" "serverless_gw" {
  for_each = toset(local.student_ids)

  control_plane_geo = var.konnect_region
  control_plane_id  = konnect_gateway_control_plane.serverless_cp[each.key].id

  dataplane_groups = [
    {
      provider = "aws"
      region   = var.konnect_region
    }
  ]

  kind = "serverless.v1"
}

# ── Config Store + Vault per student (LLM API keys) ──────────────────────────

resource "konnect_gateway_config_store" "student_config_store" {
  for_each = toset(local.student_ids)

  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
  name             = "${var.student_name_prefix}${each.key}-config-store"
}

resource "konnect_gateway_vault" "student_vault" {
  for_each = toset(local.student_ids)

  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
  name             = "konnect"
  prefix           = "ai"
  description      = "Konnect config store vault for ${var.student_name_prefix}${each.key}"
  config = jsonencode({
    config_store_id = konnect_gateway_config_store.student_config_store[each.key].id
  })
}

# ── LLM API key secrets (stored in each student's Config Store) ───────────────
# These are referenced in decK configs as {vault://ai/llm-api-key-openai} etc.
# Students never see the raw keys — Kong resolves them at request time.

resource "konnect_gateway_config_store_secret" "llm_openai" {
  for_each = toset(local.student_ids)

  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
  config_store_id  = konnect_gateway_config_store.student_config_store[each.key].id
  key              = "llm-api-key-openai"
  value            = "Bearer ${var.llm_api_key_openai}"
}

resource "konnect_gateway_config_store_secret" "llm_anthropic" {
  # Only provision if an Anthropic key has been provided (Lab 3 failover)
  # for_each = var.llm_api_key_anthropic != "" ? toset(local.student_ids) : toset([])
  for_each = toset(local.student_ids)

  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
  config_store_id  = konnect_gateway_config_store.student_config_store[each.key].id
  key              = "llm-api-key-anthropic"
  value            = "Bearer ${var.llm_api_key_anthropic}"
}

# ── expense-agent consumer + API key (pre-seeded for Lab 2+) ─────────────────

resource "konnect_gateway_consumer" "expense_agent" {
  for_each = toset(local.student_ids)

  username         = "expense-agent"
  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
}

# resource "konnect_gateway_consumer_key_auth" "expense_agent_key" {
#   for_each = toset(local.student_ids)

#   consumer_username = konnect_gateway_consumer.expense_agent[each.key].username
#   consumer_id       = konnect_gateway_consumer.expense_agent[each.key].id
#   control_plane_id  = konnect_gateway_control_plane.serverless_cp[each.key].id
#   # key is auto-generated by Konnect when omitted
# }

# ── Consumer groups for ACL-based tool scoping (Lab 2) ───────────────────────

resource "konnect_gateway_consumer_group" "expense_agents" {
  for_each = toset(local.student_ids)

  name             = "expense-agents"
  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
}

resource "konnect_gateway_consumer_group" "escalation_approved" {
  for_each = toset(local.student_ids)

  name             = "escalation-approved"
  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
}

resource "konnect_gateway_consumer_group_member" "agent_expense_agents" {
  for_each = toset(local.student_ids)

  consumer_id       = konnect_gateway_consumer.expense_agent[each.key].id
  consumer_group_id = konnect_gateway_consumer_group.expense_agents[each.key].id
  control_plane_id  = konnect_gateway_control_plane.serverless_cp[each.key].id
}

resource "konnect_gateway_consumer_group_member" "agent_escalation_approved" {
  for_each = toset(local.student_ids)

  consumer_id       = konnect_gateway_consumer.expense_agent[each.key].id
  consumer_group_id = konnect_gateway_consumer_group.escalation_approved[each.key].id
  control_plane_id  = konnect_gateway_control_plane.serverless_cp[each.key].id
}

# ── Global CORS plugin (one per control plane) ───────────────────────────────

resource "konnect_gateway_plugin_cors" "global_cors" {
  for_each = toset(local.student_ids)

  control_plane_id = konnect_gateway_control_plane.serverless_cp[each.key].id
  instance_name    = "global-cors"

  config = {
    allow_origin_absent = true
    origins             = ["*"]
    methods             = ["GET", "HEAD", "PUT", "PATCH", "POST", "DELETE", "OPTIONS", "TRACE", "CONNECT"]
    credentials         = true
    max_age             = 3600
    preflight_continue  = false
  }
}

# ── System account token (shared — used for decK syncs in lab instructions) ──

resource "konnect_system_account_access_token" "token" {
  account_id = var.system_account_id
  expires_at = timeadd(timestamp(), "8760h") # 1 year — refresh before next cohort
  name       = "${var.student_name_prefix}workshop-token"
}
